Redis add hgetall hdel
applike/gosoline pull request #470
Opened 2021-03-30 15:21 UTC by lantosgyuri

2021-03-30 15:27 UTC, selm0 requested changes

2021-03-30 15:27 UTC, selm0 commented on pkg/redis/client_test.go
> +	s.NoError(err, "there should be no error on HgetAll")
`HGetAll` (uppercase G), as that's the command name

2021-03-30 15:27 UTC, selm0 commented on pkg/redis/client_test.go
> +	s.Equal(map[string]string{"field": "value1", "field2": "value2"}, vals, "there should be no error on HSet")
You're message is misleading, as the assert does not have anything to do with `errors on HSet`.
You can either fix it or remove it.
For most assertions, we don't provide error messages, as they are just duplication the assertion itself:
e.g. s.NoError(error, "there should be no error") contains the same information twice.

2021-03-30 15:27 UTC, selm0 commented on pkg/redis/client.go
> +func (c *redisClient) HDel(ctx context.Context, key string, fields ...string) (int64, error) {
Can you please add a test for HDel aswell?

2021-03-31 06:30 UTC, j4k4 commented
do we have 2 PRs now for this? :thinking:

2021-04-13 07:13 UTC, selm0 requested changes

2021-04-13 07:13 UTC, selm0 commented on pkg/redis/client.go
> +	HDel(ctx context.Context, key string, fields ...string) (int64, error)
Please order all the methods alphabetically

2021-04-13 13:44 UTC, selm0 approved these changes

2021-04-13 13:56 UTC, merged